### ISSUE TITLE
Explicit garbage collection is bottleneck for our loop now.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#1508]
I have modified https://github.com/status-im/nim-beacon-chain/blob/devel/beacon_chain/beacon_node.nim#L610 to meter amount of time wasted inside of this call, after 6 hours of running collection takes 10seconds.
https://gist.github.com/cheatfate/11d76c26db6f7fef6a18c78684e5eef9

**Comment by mratsim** [comment]
According to https://nim-lang.org/docs/gc.html

![image](https://user-images.githubusercontent.com/22738317/90317725-9daa6880-df2b-11ea-9fcc-0001548081e3.png)

1 ms should be reasonable with acyclic references.

So I suspect the following possible causes:
- we have cyclic references (ChainDAG, but we did remove children in ChainDAG: https://github.com/status-im/nim-beacon-chain/issues/669, so I suppose those lefts are in async/futures?
- we have fragmentation
- we have too many small allocations (should be helped by using cstring instead of string for Result)

**Comment by arnetheduck** [comment]
This issue was created while we had a massive memory leak going which would lead to extremely large heaps - I have not seen this recently - it would be appropriate to create a metric that tracks GC full collection time in seconds and add it to the dashboard.

**Comment by arnetheduck** [comment]
This has been fixed with numerous memory efficiency improvements
