### ISSUE TITLE
[SEC] sync manager - accepts empty block responses

### ISSUE THREAD

**Issue by tintinweb** [status-im/nimbus-eth2#1548]
## Description

`checkResponse` validates the response to active `beaconBlocksByRange` requests. 

The [spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/p2p-interface.md#BeaconBlocksByRange) notes the following: 

> The response MUST consist of zero or more response_chunk. Each successful response_chunk MUST contain a single SignedBeaconBlock payload.

> Clients MUST keep a record of signed blocks seen since the since the start of the weak subjectivity period and MUST support serving requests of blocks up to their own head_block_root.

> Clients MUST respond with at least the first block that exists in the range, if they have it, and no more than MAX_REQUEST_BLOCKS blocks.

* Sync manager does not check if peer is actually capable of fulfilling the request
* Sync manager allows empty block responses.
* Peers can force status update requests with every iteration (score manipulation)

https://github.com/status-im/nim-beacon-chain/blob/3433c77c35f3025729ac9204ab6b91ea136dce9e/beacon_chain/sync_manager.nim#L146-L150

see References for a detailed walkthrough

## Exploit Scenario

A malicious peer may force the node to stay in the `syncWorker` loop by providing empty block responses and lying about their `headSlot`. As a side-effect, the node has to keep asking for status updates. A malicious peer may use this fact to slow down the node's syncing efforts (being barely cooperative, not providing blocks responses, providing steadily increasing peer.headSlot to force status update requests). By forcing status request the peer may be able to artificially increase its reputation.

## Mitigation Recommendation

- check if the peer is actually capable of fulfilling the block request (peer.headSlot > req.slots) and only request blocksByRange if the peer can provide them. Break otherwise. Consider discovering more peers for the peer pool if the pool only consists of uncooperative nodes.
- disallow empty responses and penalize them
- consider rewarding nodes (score) based on how cooperative they were fulfilling the request (number of blocks returned/request)
- exit `syncWorker` if the node is considered to be in sync without relying on the peer's sync status (see Ref 4)

## References

Forward sync in sync_manager `syncWorker` syncs blocks from peers by issuing `beaconBlocksByRange` requests. The manager first tries to acquire a peer from the pool (see `syncLoop`) and then passes the peer to async `syncWorker`. 

1. `syncWorker` checks if the remote peer's headslot appears to be valid `peerSlot > wallSlot + man.toleranceValue` and breaks if not
2. `syncWorker` then checks if the peer's headSlot is outdated and assumes that a status update is required`peerAge >= man.maxStatusAge:`

    * Note that a peer can artificially force a status update request by lying about its headslot / peerAge potentially blocking the future (status request) up to what is configured for the response timeout.

3. it is verified that the new headslot is > than the previous one, otherwise the sync loop is exited because the peer is assumed to be stale. 

    * Note that a peer may still provide an outdated headslot that is at least +1 the previous to make `syncWorker` continue the loop (and block a worker by just slowly fulfilling requests or not fulfilling them at all)
    * Note that the peer might not be stale but super slow in updating its own blocks. Such a peer might not be very useful for the node and should be discarded. 
    * Note that score is adjusted `PeerScoreGoodStatus (+50)` for providing a valid status answer. This might be used to some extent for a node to increase its own reputation. However, in this case only during the initial sync loop and only up to the max reputation. Still, a malicious node may use this to compensate for potential future penalties.
    * Detecting that the peer is stale does not have an effect on the peer pool. The stale peer might be selected for another iteration.

4. it is checked whether the node is in sync with the peer AND the chain

    * Note: the condition to stop this worker is probably already met if `headAge <= man.maxHeadAge` is true without having to check the distance of the peer.headSlot to wallSlot `peerAge <= man.maxHeadAge`. In the worst-case our headAge is close to the tip but the client still reports a peerAge that is > `man.maxHeadAge` causing the sync loop to continue.
    * Note: the peer may be able to make the first check fail if they initially reported a low peer.headSlot. They may be able to do this for a number of iterations by providing slowly increasing `peer.headSlot` when updating the status forcing the node to request a status update with every loop. They may still report an outdated headslot after the update and be uncooperative (empty block responses) when syncing.

https://github.com/status-im/nim-beacon-chain/blob/3433c77c35f3025729ac9204ab6b91ea136dce9e/beacon_chain/sync_manager.nim#L743-L748

5. Blocks from the peer are requested. However, it was never checked if the peer can actually fulfill the request to provide the blocks (peer.headSlot <= req.slot).

    * If the peer is unable to provide blocks its score might be decreased, even though it was honest and shouldn't have been called at all.
    * If the request succeeds but the peer provides an empty list of blocks, `checkResponse` passes, even though no blocks were returned. This might be used to keep the node busy asking the malicious peer for blocks with the malicious peer not returning any to slow down the nodes syncing efforts (depending on `maxWorkersCount` and the number of malicious peers in pool)

**SyncWorker** 

https://github.com/status-im/nim-beacon-chain/blob/3433c77c35f3025729ac9204ab6b91ea136dce9e/beacon_chain/sync_manager.nim#L659-L819

**Comment by arnetheduck** [comment]
> disallow empty responses and penalize them

It is worth noting that an empty response (no blocks sent) is valid as long as there were no blocks in the range - for example on Medalla, there exists a range where there are no blocks for ~800 slots. Thus, to resolve this issue, one needs to remember that a peer sent an empty response then penalize them afterwards if it turns out that there were indeed blocks in the range, and that history was chosen as the canonical history by the fork choice.

**Comment by cheatfate** [comment]
Number of changes was made to forward syncing algorithm so i'm going to explain what was made for mentioned problems.

#### Sync manager does not check if peer is actually capable of fulfilling the request

`peerSlot` is the latest known information about peer's head slot. We using this slot number to obtain request from `SyncQueue`  https://github.com/status-im/nim-beacon-chain/blob/devel/beacon_chain/sync_manager.nim#L802. If `SyncQueue` could not satisfy our request - EmptyRequest will be returned and we will fall into sleep for `RESP_TIMEOUT` time and after we release this peer. So there present a chance that we will get much better peer from PeerPool, on next step of iteration.

#### Sync manager allows empty block responses.

According to specification empty responses is something we could meet in the network. But there present an issue that we could reward peers for an empty responses. We could check if empty response valid only when we get at least one non-empty response, and this could not happen for a long time (800 slots in medalla).

#### Peers can force status update requests with every iteration (score manipulation).
This was fixed in https://github.com/status-im/nimbus-eth2/pull/1827

**Comment by tintinweb** [comment]
(review: a0a4526c8347b12a672d3b1d333505f4572119c0 /misc-fixes)

LGTM!
