### ISSUE TITLE
Enhancement request: Logs to CONSOLE

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth2#1764]
- Nimbus beacon node v0.5.0 (da3102c0)
- Dockerized environment, buster-slim
- Logs flow into a file inside the container

Suggested enhancement: A command-line flag that allows choosing a log destination, possible values FILE, CONSOLE, and BOTH. Other additional destinations (SYSLOG anyone?) as you see fit.

Rationale: CONSOLE logs are highly desirable in dockerized environments, they allow a peek at the function of a container app with commands like `docker-compose logs -f beacon`

**Comment by arnetheduck** [comment]
We've been logging to console since mainnet for sure - there's also a `--log-file` option, also since mainnet.

Next release will improve on this situation by providing options to control both destinations, but as far as this issue goes, it should "just work" - not sure why we didn't close it long ago :)
