### ISSUE TITLE
Ship binary releases for the beacon node

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#1832]
We should make it more practical for users to download and run Nimbus without setting up a development environment. As a first step, we'll start publishing pre-compiled binaries for Windows, macOS and Linux and images on docker hub.

The reliance on Makefile targets will be reduced through more reasonable defaults and config files for the official testnets.

Setting up system services will be simplified through a new `beacon_node configure` command

**Comment by stefantalpalaru** [comment]
Interesting project for cross-compiling Windows binaries on Linux: https://mxe.cc/

A better strategy for generating reproducible Docker Debian images, by using package repository snapshots: https://blog.beuc.net/posts/Reproducible_Windows_builds/

**Comment by stefantalpalaru** [comment]
We can now generate a reproducible 64-bit Linux binary that's dynamically linked only to Glibc. We do this inside an Ubuntu 20.04 Docker container that has Glibc 2.31.

This binary will not run on Glibc versions older than 2.29, due to these versioned dynamic symbols:

```text
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.29  log
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.29  pow
```

(no, we cannot statically link libm: https://bugzilla.redhat.com/show_bug.cgi?id=1433347 - and that would only get us down to 2.28 from which we need `fcntl64`)

A list of Glibc versions in various Linux distributions: https://repology.org/project/glibc/versions

**Comment by tersec** [comment]
> that would only get us down to 2.28 from which we need `fcntl64`

Presumably, Nimbus doesn't simply fail to compile against glibc older than 2.28, in which case it's able to substitute some other symbol.

**Comment by stefantalpalaru** [comment]
Of course we can compile it on older distros, in order to support an older Glibc, but how many bugs and missing optimisations are we willing to accept in the name of binary compatibility?

**Comment by tersec** [comment]
Oh, I agree with the current course of action you're proposing. If we get too many complaints from users of older distributions, we an reassess, but starting with 20.04LTS seems like a fine default.

**Comment by zah** [comment]
Remaining items:

* Prepare binaries for Windows and macOS

**Comment by stefantalpalaru** [comment]
Windows binaries added here: https://github.com/status-im/nimbus-eth2/pull/2292

macOS binaries added here: https://github.com/status-im/nimbus-eth2/pull/2559

And with that we covered all the targets we wanted, for our binary distribution.
