### ISSUE TITLE
Implement various heuristics for detecting potential configuration errors that may lead to slashing

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#1834]
The gossip traffic can be monitored for conflicting non-local activity from validators that are attached locally. This should shut down the activity of the specific validators without shutting down the entire client. Persistent records may be written to enforce the conservative behaviour on restart. Potential UI solutions for diagnosing the problem and the resulting conditions should be discussed with the community.

**Comment by tersec** [comment]
For reference, some things I investigated but didn't do:

- smuggle side-channel data through existing p2p-interface messages (attestations, proposerslashings, etc). In general, creating realistic enough messages to be propagated created too many undesireable side-effects, to the extent it would even be permitted, and no such mechanism could hold long, because by its nature, it'd be functioning as a protocol exploit;

- coordination without explicit communication by other (non-random) means. These tended to require more assumptions than I was comfortable with and create odd edge-cases and different behaviors depending on whether nodes were on one system, on different systems in the same network, on entirely different types of systems, etc; and

- on the Gossip layer, open targeted topics without these constraint (for example, for up to 4M validators, use the first 13 to 16 bits or so worth of the public key to knock that down to a few hundred validators per presence-pinging, along with other ways to dodge the essentially O(n^2) nature of this this in a decentralized network). There are much better approaches there, and that might be worth investigating, but it'd require broader cooperation and integration with the Eth2 incentive structure to do well, and could somewhat externalize costs onto libp2p layers which otherwise only have to deal with ~70 topics, and/or discovery v5 implementations. If one had this, one could simply sign almost an empty message with one's validator private key and broadcast it, and that'd be one simple approach. But it's not near-term enough.

**Comment by tersec** [comment]
Doppelganger detection has been implemented and released.
