### ISSUE TITLE
make nimbus_beacon_node progress bar

### ISSUE THREAD

**Issue by unixpi** [status-im/nimbus-eth2#1923]
**Is your feature request related to a problem? Please describe.**
`make nimbus_beacon_node` hangs for a long time, it's unclear if it's progressing as expected or if something has gone wrong. I've noticed I prefer running it with the `V = 1` option in order to receive feedback.

**Describe the solution you'd like**
Some sort of progress bar at the bottom that estimates time left until beacon node has been built (or percentage achieved).

**Describe alternatives you've considered**
Making `V=1` the default. Upon further consideration I don't think this is a great idea as there are places where it still hangs for a long time, and the messages can be confusing.

**Comment by arnetheduck** [comment]
the canonical solution here really is to not use `make` to launch the node - ie users don't need to recompile just to relaunch, generally. what stands in the way is that we don't have config files really, but these are also not needed really - a shell script that launches the client is equivalent to a config file.

**Comment by unixpi** [comment]
Got it. I think it would still be useful on first launch (this is probably when you're most uncertain as to whether things are working as they should be).  When upgrading too.

**Comment by sachayves** [comment]
@arnetheduck alternatively we could just have a friendly message that lets the user know this may take some time.

**Comment by zah** [comment]
Recent feedback for our build scripts:

> "Only by using the -j4 parameter, it compiles in 10 minutes, but before
asking them on discord I took some time to understand because I would
not know if the compiler was stuck or still working
Their recommendation is to use the -j4 parameter,  but that is not even
in the documentation. Prysm for example has a sh that you simply execute
and it already logs everything that is happening. Teku does the same and
even has a timer so you know it is still compiling, both take just a
couple of minutes. Nimbus also logs the compiling tasks, but at one
point it just logs compiling beacon_node and it stays there until it is
compiled, which without the -j4 flag is around 50 minutes in our case.
We did not try the docker as the documentation says to build it from
source, so we followed that. "

**Comment by tersec** [comment]
Sure, and having `-j` (or `-j$(nproc)`) as a default is probably better here than a progress bar.

**Comment by arnetheduck** [comment]
Since building from source has been supplanted by binaries as the primary delivery method for users, this is no longer relevant from a user UX perspective - closing here, though in the future this might be valuable to consider for nimble (cc @yyoncho @zah )
