### ISSUE TITLE
Nimbus book: recommended hardware specs

### ISSUE THREAD

**Issue by sachayves** [status-im/nimbus-eth2#1936]
Processor, memory, storage, internet (anything else?)

**Comment by tersec** [comment]
Some main system requirements are:

- enough RAM (I've seen up to 3GB resident on Medalla recently, just as an anecdote) and

- one major distinction is platforms which supports BLST and which don't. This means (as I understand it) x864-64 which supports SSSE3 (https://en.wikipedia.org/wiki/SSSE3#CPUs_with_SSSE3) or 64-bit ARMv8. BLST is quite preferred, I believe on the order of 2.5x faster (though @mratsim would know better on this point). Functionally, we should work on 32-bit ARM/x86, but not recommended.

**Comment by sachayves** [comment]
Does a Pi 4 support BLSt?

**Comment by tersec** [comment]
> Does a Pi 4 support BLSt?

Yes, if it's running a 64-bit OS. Ditto a Pi 3. If "The Raspberry Pi 2 V1.2 was upgraded to a Broadcom BCM2837 SoC with a 1.2 GHz 64-bit quad-core ARM Cortex-A53 processor,[37] the same SoC which is used on the Raspberry Pi 3" is to be believed from https://en.wikipedia.org/wiki/Raspberry_Pi#Processor, so does a Pi 2 V1.2 in theory, but since the Pi 2 didn't in general, I'm not sure if any distros target 64-bit support for that specific version of the Pi 2.

But a Pi 3 or Pi 4 should be safe on the BLST end, given a 64-bit OS.
