### ISSUE TITLE
Post-mainnet branch structure

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nimbus-eth2#2163]
Currently, we have 2 main branches, `master` and `devel` - we merge things into `devel` and then occasionally to `master` on release. `master` more or less follows the releases, while `devel` has potentially all crazy changes.

On top of that, we have `nim-libp2p-auto-bump` which gets the latest libp2p changes, but occasionally serves as a wild-west branch.

Instead, I'd suggest the following structure:

* `stable` - release branch, more or less current `master`, tracks latest released version
* `testing` - pre-release branch - reasonably safe changes / bug fixes and tested features go here - close to current `devel` but slightly more stable
* `unstable` - wild-west branch, a mix between `devel` and `nim-libp2p-auto-bump` - here we put features, libp2p auto-bumps and anything else that should get more testnet testing - in particular, this should be the "default" merge base branch from which _features_ are developed - bugfixes can go straight to unstable.

The names are of course derived from `debian` that has a similar policy.

De-facto, this is similar to what we have today, but we formalize testing of features on the `unstable` branch, merging them in there more aggressively, and making sure that the autobump job doesn't overwrite them (and instead creates new commits), while fast-tracking pure bugfixes on `testing`.

In terms of testing, this would mean:

* `testing` and `unstable` will run a larger part of pyrmont, taking nodes and validators from current `master` - in particular, we introduce low-validator-count nodes on each of those
* `mainnet` bootstrap nodes will run on `testing`

The main downside I see with this approach is the ambiguity between `testing` and `unstable` - the upside is that it makes it easier to make bugfix releases without introducing untested features. 

It also introduces slightly more work: feature branches must be merged to `testing` and `unstable` separately by _someone_ - presumably the original author once the feature has been running comfortably in the `unstable` pyrmont environment for a bit.

**Comment by tersec** [comment]
From Debian's experience, one effect is that security fixes there's a tension between the existence/appeal of `testing` and security fixes. `testing` looks appealing because it's more updated than `stable`, but not as unstable as `unstable`. However, its neither direct target of quick security fixes upstream changes (that's `unstable`/`experimental`) or an also-supported branch which gets priority fixes (`stable`).

This is an acute tension in Debian because of the time period between `stable` releases (~1.5 - 2 years on average). This structure can work better if either one commits to (a) not-too-long (obviously, we'd not be doing 1.5 year-long releases, but by Eth2 client standards) `stable` release periods, and/or (b) ensure `testing` has relevant hotfixes.

**Comment by arnetheduck** [comment]
Indeed, the intent would be to keep `testing` and `unstable` relatively close but still get some canary or a/b testing done on features - the objective is to use the shared testing infrastructure we already have without going over-the-top - over-the-top solutions would be to run a separate test environment like `unstable` for _every_ PR.

**Comment by mratsim** [comment]
In the near future I see 2 features that might need a long testing period on Pyrmont:

1. Slashing protection refactoring with DB schema change and the need to support both the old and new format at the same time.
2. Introducing batch signature verification at the block level.

Change 1 shouldn't be much work to rebase regularly on `testing` because it's in a pretty isolated area of the code.
Change 2 requires:
- introducing a new type across all consensus: VerifiedBlock
- some rework in the gossip -> consensus layer
which might be a bit more costly to rebase on testing.

we could put those in unstable but do we really want to test those together or shouldn't we test unstable risky features in isolation?

One thing that might be possible is having a Github Actions that notifies when an open PR against `testing` cannot be applied anymore and we keep each risky feature in "unstable-slashing", "unstable-batch-verification". Benefits isolated unstable features and safe merging, cost: branch overhead and features not tested together.
Another approach is the unstable branch where everything goes. Benefits: features tested together, similar to our current way of working, cost: cherry-pick overhead for testing, isolating regressions, isolating what actually improved performance.

**Comment by arnetheduck** [comment]
> we could put those in unstable but do we really want to test those together or shouldn't we test unstable risky features in isolation?

perfect isolation would be nice, but also consumes a lot of resources and is hard to pull off - ie we'd have to introduce infrastructure to spin up pyrmont nodes with validators for every PR and close them after - sure, it's a nice thing, but also a lot of work to pull off correctly.. keep in mind that into `unstable`, we would put things that have passed the "normal" PR checks already: unit tests, finalization tests etc and are now ready to run on a couple of pyrmont nodes for a slightly longer integration test

**Comment by zah** [comment]
Since this RFC has been accepted, I'm closing the issue. The remaining work is to update our infrastructure scripts and documentation to use the new branches.
