### ISSUE TITLE
Add cross-compiled targets in our Makefiles

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#766]
Our Makefiles should offer an easy way to cross-compile the beacon node to a portable executable (statically linked) for various targets:

* [ ] 64-bit ARM (v6, v7, v8). Intended to run on the various flavours of Raspberry Pi under Linux.
* [ ] WASM (WASI). Intended to run under [Wasmer](https://github.com/wasmerio/wasmer). An additional target here should execute the test suite.
* [ ] x64 Windows (cross-compiled with MingW from Linux).

**Comment by arnetheduck** [comment]
WASI would need upstream support from nim - which is a bit difficult because of all the junk in `system.nim` and the usage exceptions in general - for wasm, a more realistic option for now is to target emscripten which provides a C/syscall emulation layer as well as an exception emulation layer that calls out into the javascript runtime - see https://github.com/status-im/nim-beacon-chain/blob/master/wasm/build.sh

**Comment by syrusakbary** [comment]
I think Wasienv might be able to solve the Wasm WASI needs easily!

https://github.com/wasienv/wasienv

**Comment by stefantalpalaru** [comment]
I wouldn't call it "easy", but we already do cross-compilation to generate distribution binaries: https://github.com/status-im/nimbus-eth2/blob/8b15c5d75f55007635cb1656b5c525196336847c/docker/dist/entry_point.sh
