### ISSUE TITLE
Address remaining items in the beacon-node/validator-client split

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#767]
This depends on: https://github.com/status-im/nim-beacon-chain/issues/723

The responsibilities of the validator client and mechanisms for interaction with the beacon node are described here:
https://github.com/ethereum/eth2.0-APIs/blob/master/apis/validator/README.md

In our current codebase, `validator_pool.nim` stores all attached validators and acts as an abstraction that may be replaced with a pool of connections to external validator client processes. The goal of this bounty is to introduce RPC end-points matching the official APIs (even if not using the official RESTful HTTP transport) and to finish the validator pool and client implementations.

Please note that the number of attached validator clients per beacon node is unlimited and some parallelism must be introduced in the communication with them in order to avoid the situation where a single high latency validator introduces unwanted delays in the communications with the others.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/976

**Comment by tersec** [comment]
What's the status of this?

**Comment by onqtam** [comment]
I'll provide a short writeup in a couple of hours

**Comment by onqtam** [comment]
- this unfinished PR (which addresses the changes that the attester duties should now be fetched using validator ids instead of pubkeys and that it is now [POST instead of GET](https://github.com/ethereum/eth2.0-APIs/pull/93)): TODO
- currently the VC aggregates the attestations for the current slot whereas the beacon node aggregates for 1 slot earlier (`TRAILING_DISTANCE`). Not sure how to request an aggregate for 1 slot earlier because the VC probably doesn't have the attestation data root for the previous slot (it could if it was attesting and has saved that, but it's not guaranteed) - see this discussion for reference: https://github.com/status-im/nimbus-eth2/pull/1644/files#r487852112
- currently the makefile targets send the BN looking at a dummy directory for the validators and the VC is given the actual data dir - this is perhaps error prone - haven't tested what would happen if both the BN & the VC are pointed at the same validators (if the slashing protection will work, etc)
- currently `eth2_network_simulation` fails to finalize at around slot 200 (or 600 or whatever) when the validators are split 50/50 between the BNs & the VCs (on by default) because more and more validators miss their attestations. However the makefile VC targets work flawlessly for days with the medalla/spadina testnets and never missed an attestation (with inclusion distance of `0`) - or block proposals!
- the fork schedule is not taken into account (`/eth/v1/config/fork_schedule`) - instead we fetch the current fork at the start of each epoch using `/eth/v1/beacon/states/{state_id}/fork`
- no events are pushed from the BN to the VC - for example the chain reorganization event should trigger the re-fetching of attester/proposer duties (the right place in the BN to trigger that is where `beacon_reorgs_total` is incremented - perhaps with some callback)
- [`/eth/v1/validator/beacon_committee_subscriptions`](https://ethereum.github.io/eth2.0-APIs/#/ValidatorRequiredApi/prepareBeaconCommitteeSubnet) is not implemented/used at all
- fuzzing the API
- move to REST instead of json-rpc

**Comment by tersec** [comment]
https://github.com/ethereum/eth2.0-specs/blob/v1.0.0/specs/phase0/validator.md#protection-best-practices formalizes this VC/BN split more.

**Comment by tersec** [comment]
The validator client has since been rewritten entirely, using the REST API rather than JSON RPC.
