### ISSUE TITLE
Long computations on the main/networking thread

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth2#968]
We have several expensive computations (over 1 ms) that prevent NBC from handling network and IO events.

Either we need to insert some `poll()` at choice places or we need to use background thread(s).

Expensive computations:
- `updateStateData` (blockpool): https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/block_pool.nim#L800-L847
- `withState`(blockpool): https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/block_pool.nim#L26-L40
- `state_transition` (state_transition): https://github.com/status-im/nim-beacon-chain/blob/01e9df97cb2f0035df2f7cea72ef14213eb0cc0f/beacon_chain/state_transition.nim#L185-L248
- signatures and RANDAO, in particular `signAttestation` is called in burst every 6 seconds once per attached validators: https://github.com/status-im/nim-beacon-chain/blob/9636ca3e17628d4bfbdc2a29006e5385fc398e66/beacon_chain/validator_pool.nim#L27-L77

**Comment by arnetheduck** [comment]
Generally, to determine a safe threshold, one would have to look at timeouts involved in the various protocols - 1ms is kind of arbitrary - there's no inherent advantage reading network requests from the OS socket and placing them on an internal "handling" queue as opposed to leaving them in the OS buffer - in fact, it's worse, unless you can truly parallelize the work because you're just moving the backlog from one place to another - as long as required periodic work happens reasonably on time, it's fine.

Now, onto the specifics:

`withState`/`updateStateData`: fast because they just replay existing stuff, should be <1ms per epoch (eventually), these are the same actually - missing caches presently - risk factor: empty slot processing when there's no finalization

`state_transition`: slow for unverified blocks - basically boils down to signature check, because `hash_tree_root` can likely be made "fast enough" to disappear from the `perf` trace, otherwise see above

`signAttestation` / block&attestation production - with a split validator/beacon client, the signature happens in one or more other processes

One big culprit missing is `sync`, and the backward variety in particular: when syncing blocks, we build up a queue of unverified blocks then verify them all in a single go because until we have earlier blocks, we can't sync the later ones. Forward sync is better but might run into the same problem when syncing blocks from multiple peers - "poll" or trickling block verification here would need some thought.

**Comment by cheatfate** [comment]
Our current syncing performance is limited by block processing performance, on my PC for `schlesi` network i have performance ~4 blocks per second.

**Comment by arnetheduck** [comment]
this is now balanced more or less by `eth2_processor` - if there are still long-running tasks, let's open new issues
